// // This file is automatically generated. Do not edit it directly.
// import { createClient } from "@supabase/supabase-js";
// import type { Database } from "./types";

// const SUPABASE_URL = (import.meta as unknown as { env: Record<string, string> }).env.SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = (import.meta as unknown as { env: Record<string, string> }).env.SUPABASE_PUBLISHABLE_KEY;

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(
//   SUPABASE_URL,
//   SUPABASE_PUBLISHABLE_KEY,
//   {
//     auth: {
//       storage: localStorage,
//       persistSession: true,
//       autoRefreshToken: true,
//     },
//   },
// );

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = (import.meta as unknown as { env: Record<string, string> })
  .env.SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta as unknown as { env: Record<string, string> }
).env.SUPABASE_PUBLISHABLE_KEY as string;

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

// ── Basic Supabase helpers (replaces edge functions) ────────────────────────

export async function saveConversationToDB(opts: {
  visitorName?: string;
  visitorCompany?: string;
  visitorRole?: string;
  visitorIntent?: string;
  summary?: string;
  metadata?: Record<string, unknown>;
}): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from("conversations")
      .insert({
        visitor_name: opts.visitorName ?? null,
        visitor_company: opts.visitorCompany ?? null,
        visitor_role: opts.visitorRole ?? null,
        visitor_intent: opts.visitorIntent ?? null,
        summary: opts.summary ?? null,
        metadata: opts.metadata ?? {},
      })
      .select("id")
      .single();

    if (error) {
      console.warn("[Supabase] saveConversation error:", error.message);
      return null;
    }
    return data?.id ?? null;
  } catch (e) {
    console.warn("[Supabase] saveConversation threw:", e);
    return null;
  }
}

export async function saveMessagesToDB(
  conversationId: string,
  messages: Array<{ role: "user" | "ai"; text: string; ts: number }>,
): Promise<void> {
  if (!conversationId || !messages.length) return;
  try {
    const rows = messages.map((m) => ({
      conversation_id: conversationId,
      role: m.role === "ai" ? "assistant" : "user",
      content: m.text,
      metadata: { ts: m.ts },
    }));
    const { error } = await supabase.from("messages").insert(rows);
    if (error) console.warn("[Supabase] saveMessages error:", error.message);
  } catch (e) {
    console.warn("[Supabase] saveMessages threw:", e);
  }
}
